-- Database firmadigital
\set dbname_SIGNATURE `echo $DB_NAME_SIGNATURE`
\set user_SIGNATURE `echo $DB_USER_SIGNATURE`
\set password_SIGNATURE `echo $DB_PASS_SIGNATURE`

CREATE USER :user_SIGNATURE WITH PASSWORD :'password_SIGNATURE';
ALTER ROLE :user_SIGNATURE WITH SUPERUSER;
CREATE DATABASE :dbname_SIGNATURE WITH OWNER :user_SIGNATURE;
GRANT ALL PRIVILEGES ON DATABASE :dbname_SIGNATURE to :user_SIGNATURE;
